spring:
  application:
    name: boot3-01-demo
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/boot3?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: cpf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

person:
  name: cpf
  age: 18
  birthday: 2023/10/01
  like: true
  cats:
    cat1:
      name: 怦怦
      age: 2
    cat2: {name: 可乐, age: 3}
  dogs:
    - name: dog1
      age: 2
    - name: dog2
      age: 3
  child:
    name: c_son
    age: 3
    hobbies:
      - "soccer"
      - "basketball"
      - |
        - "swimming"
        - "reading"
        - "running"
        - "coding"
      - >
        - "唱"
        - "跳"
        - "rap"
        - "篮球"